### ISSUE TITLE
Add a Gitter Chat Badge to `README.md`

### ISSUE THREAD

**Issue by Hiteshgautam01** [scorelab/soundcom#6]
Place a badge on the README.md file near the top in a spot/order that helps us to promote people joining out Gitter channel. They can ask questions and just say hi.

**Comment by harshendrashah** [comment]
https://www.google.com/url?q=https://gitter.im/scorelab/scorelab&sa=D&ust=1538166643433000&usg=AFQjCNHCWw6TLgciNIYtZUgHHoiImbirzw

Would it be fine if I add this link to the badge?
